# Generated by Django 5.2.6 on 2025-10-27 17:56

import volunteer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_application_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aadhar_card_back',
            field=models.FileField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AddField(
            model_name='application',
            name='aadhar_card_front',
            field=models.FileField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=volunteer.models.volunteer_directory_path),
        ),
    ]
