# Generated by Django 5.2.6 on 2025-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_volunteer_aadhar_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='can_view_member_data',
            field=models.BooleanField(default=False),
        ),
    ]
