# Generated by Django 5.2.6 on 2025-10-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_volunteer_can_view_member_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hindi_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
