# Generated by Django 5.2.6 on 2025-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_application_hindi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='level_hindi_value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
