# Generated by Django 5.2.6 on 2025-11-07 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0011_rename_name_hindi_volunteer_hindi_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='affidavit',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='affidavit',
        ),
        migrations.AddField(
            model_name='application',
            name='referred_by_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_volunteers_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='referred_by_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
