# Generated by Django 5.2.6 on 2025-11-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_remove_application_affidavit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerWorkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_areas', to='volunteer.volunteer')),
            ],
        ),
    ]
