# Generated by Django 5.2.6 on 2025-10-19 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyapari', '0003_advertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vyapari',
            name='business_type',
        ),
        migrations.AddField(
            model_name='vyapari',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vyapari_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vyapari',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
