# Generated by Django 5.2.6 on 2025-10-20 17:37

import vyapari.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyapari', '0004_remove_vyapari_business_type_vyapari_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vyapari',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=vyapari.models.vyapari_directory_path),
        ),
        migrations.AddField(
            model_name='vyapari',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=vyapari.models.vyapari_directory_path),
        ),
        migrations.AddField(
            model_name='vyapari',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=vyapari.models.vyapari_directory_path),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('global', 'Global'), ('district', 'District'), ('market', 'Market'), ('state', 'State')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vyapari',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=vyapari.models.vyapari_directory_path),
        ),
        migrations.AlterField(
            model_name='vyapari',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vyapari.models.vyapari_directory_path),
        ),
    ]
