# Generated by Django 5.2.6 on 2025-10-20 17:43

import vyapari.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyapari', '0005_vyapari_image1_vyapari_image2_vyapari_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vyapari',
            name='employee_count',
        ),
        migrations.AddField(
            model_name='vyapari',
            name='visiting_card',
            field=models.ImageField(blank=True, null=True, upload_to=vyapari.models.vyapari_directory_path),
        ),
    ]
