# Generated by Django 5.2.6 on 2025-10-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_options_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
